// Package swagger_docs Code generated by swaggo/swag. DO NOT EDIT
package swagger_docs

import "github.com/swaggo/swag"

const docTemplaterestricted = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache-2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aux-deployments": {
            "get": {
                "description": "List auxiliary deployments for the current deployment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Get auxiliary deployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by aux deployment ids",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by labels (e.g.: k1=v1,k2=v2,k3)",
                        "name": "labels",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by image",
                        "name": "image",
                        "in": "query"
                    },
                    {
                        "enum": [
                            -1,
                            1
                        ],
                        "type": "integer",
                        "description": "filter if enabled",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "include assets",
                        "name": "assets",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "include container info",
                        "name": "container_info",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "auxiliary deployments",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.AuxDeployment"
                            }
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new auxiliary deployment for the current deployment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Create auxiliary deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "force pull image",
                        "name": "force_pull_img",
                        "in": "query"
                    },
                    {
                        "description": "aux deployment data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AuxDepReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments-batch/delete": {
            "patch": {
                "description": "Remove auxiliary deployments for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Delete auxiliary deployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by aux deployment ids",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by labels (e.g.: k1=v1,k2=v2,k3)",
                        "name": "labels",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by image",
                        "name": "image",
                        "in": "query"
                    },
                    {
                        "enum": [
                            -1,
                            1
                        ],
                        "type": "integer",
                        "description": "filter if enabled",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "force delete",
                        "name": "force",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments-batch/restart": {
            "patch": {
                "description": "Restart auxiliary deployments for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Restart auxiliary deployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by aux deployment ids",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by labels (e.g.: k1=v1,k2=v2,k3)",
                        "name": "labels",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by image",
                        "name": "image",
                        "in": "query"
                    },
                    {
                        "enum": [
                            -1,
                            1
                        ],
                        "type": "integer",
                        "description": "filter if enabled",
                        "name": "enabled",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments-batch/start": {
            "patch": {
                "description": "Start auxiliary deployments for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Start auxiliary deployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by aux deployment ids",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by labels (e.g.: k1=v1,k2=v2,k3)",
                        "name": "labels",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by image",
                        "name": "image",
                        "in": "query"
                    },
                    {
                        "enum": [
                            -1,
                            1
                        ],
                        "type": "integer",
                        "description": "filter if enabled",
                        "name": "enabled",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments-batch/stop": {
            "patch": {
                "description": "Stop auxiliary deployments for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Stop auxiliary deployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "filter by aux deployment ids",
                        "name": "ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by labels (e.g.: k1=v1,k2=v2,k3)",
                        "name": "labels",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by image",
                        "name": "image",
                        "in": "query"
                    },
                    {
                        "enum": [
                            -1,
                            1
                        ],
                        "type": "integer",
                        "description": "filter if enabled",
                        "name": "enabled",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments/{id}": {
            "get": {
                "description": "Get an auxiliary deployment for the current deployment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Get auxiliary deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "aux deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "include assets",
                        "name": "assets",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "include container info",
                        "name": "container_info",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "auxiliary deployment",
                        "schema": {
                            "$ref": "#/definitions/model.AuxDeployment"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove an auxiliary deployment for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Delete auxiliary deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "aux deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "force delete",
                        "name": "force",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": " job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an auxiliary deployment for the current deployment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Update auxiliary deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "aux deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "do an incremental update",
                        "name": "incremental",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "force pull image",
                        "name": "force_pull_img",
                        "in": "query"
                    },
                    {
                        "description": "aux deployment data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AuxDepReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments/{id}/restart": {
            "patch": {
                "description": "Restart an auxiliary deployment for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Restart auxiliary deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "aux deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments/{id}/start": {
            "patch": {
                "description": "Start an auxiliary deployment for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Start auxiliary deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "aux deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/aux-deployments/{id}/stop": {
            "patch": {
                "description": "Stop an auxiliary deployment for the current deployment.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Auxiliary Deployments"
                ],
                "summary": "Stop auxiliary deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "aux deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dep-advertisements": {
            "get": {
                "description": "Get all advertisements for the current deployment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment Advertisements"
                ],
                "summary": "Get advertisements",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "advertisements",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.DepAdvertisement"
                            }
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dep-advertisements-batch": {
            "put": {
                "description": "Create or update advertisements for the current deployment.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Deployment Advertisements"
                ],
                "summary": "Create / Update advertisements",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "advertisement data",
                        "name": "advertisements",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/model.DepAdvertisementBase"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove advertisements for the current deployment.",
                "tags": [
                    "Deployment Advertisements"
                ],
                "summary": "Delete advertisements",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dep-advertisements/{ref}": {
            "get": {
                "description": "Get an advertisement for the current deployment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment Advertisements"
                ],
                "summary": "Get advertisement",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "advertisement reference",
                        "name": "ref",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "advertisement",
                        "schema": {
                            "$ref": "#/definitions/model.DepAdvertisement"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Create or update an advertisement for the current deployment.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Deployment Advertisements"
                ],
                "summary": "Create / Update advertisement",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "advertisement reference",
                        "name": "ref",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "advertisement data",
                        "name": "advertisement",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DepAdvertisementBase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove an advertisement for the current deployment.",
                "tags": [
                    "Deployment Advertisements"
                ],
                "summary": "Delete advertisement",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "advertisement reference",
                        "name": "ref",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/discovery": {
            "get": {
                "description": "Query deployment advertisements.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment Advertisements"
                ],
                "summary": "Query advertisements",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filter by module ID",
                        "name": "module_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by origin",
                        "name": "origin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter by reference",
                        "name": "ref",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "advertisements",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.DepAdvertisement"
                            }
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Get basic service and runtime information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Info"
                ],
                "summary": "Get service info",
                "responses": {
                    "200": {
                        "description": "info",
                        "schema": {
                            "$ref": "#/definitions/lib.SrvInfo"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "List all jobs for the current deployment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment Jobs"
                ],
                "summary": "List jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "pending",
                            "running",
                            "canceled",
                            "completed",
                            "error",
                            "ok"
                        ],
                        "type": "string",
                        "description": "status to filter by",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "sort in descending order",
                        "name": "sort_desc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "list jobs since timestamp",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "list jobs until timestamp",
                        "name": "until",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "jobs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/lib.Job"
                            }
                        }
                    },
                    "400": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{id}": {
            "get": {
                "description": "Get a job for the current deployment.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment Jobs"
                ],
                "summary": "Get job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "job",
                        "schema": {
                            "$ref": "#/definitions/lib.Job"
                        }
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs/{id}/cancel": {
            "patch": {
                "description": "Cancel a job for the current deployment.",
                "tags": [
                    "Deployment Jobs"
                ],
                "summary": "Cancel job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment ID",
                        "name": "X-MGW-DID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "error message",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "lib.Job": {
            "type": "object",
            "properties": {
                "canceled": {
                    "type": "string"
                },
                "completed": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "error": {
                    "$ref": "#/definitions/lib.JobErr"
                },
                "id": {
                    "type": "string"
                },
                "result": {},
                "started": {
                    "type": "string"
                }
            }
        },
        "lib.JobErr": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "lib.MemStats": {
            "type": "object",
            "properties": {
                "alloc": {
                    "type": "integer"
                },
                "alloc_total": {
                    "type": "integer"
                },
                "gc_cycles": {
                    "type": "integer"
                },
                "sys_total": {
                    "type": "integer"
                }
            }
        },
        "lib.SrvInfo": {
            "type": "object",
            "properties": {
                "mem_stats": {
                    "$ref": "#/definitions/lib.MemStats"
                },
                "name": {
                    "type": "string"
                },
                "up_time": {
                    "$ref": "#/definitions/time.Duration"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "model.AuxDepContainer": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "info": {
                    "$ref": "#/definitions/model.ContainerInfo"
                }
            }
        },
        "model.AuxDepReq": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "image": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "ref": {
                    "description": "only required by create method",
                    "type": "string"
                },
                "run_config": {
                    "$ref": "#/definitions/model.AuxDepRunConfig"
                },
                "volumes": {
                    "description": "{name:mntPoint}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "model.AuxDepRunConfig": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "pseudo_tty": {
                    "type": "boolean"
                }
            }
        },
        "model.AuxDeployment": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "container": {
                    "$ref": "#/definitions/model.AuxDepContainer"
                },
                "created": {
                    "type": "string"
                },
                "dep_id": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "description": "uuid",
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "run_config": {
                    "$ref": "#/definitions/model.AuxDepRunConfig"
                },
                "updated": {
                    "type": "string"
                },
                "volumes": {
                    "description": "{name:mntPoint}",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ContainerInfo": {
            "type": "object",
            "properties": {
                "image_id": {
                    "description": "docker image id",
                    "type": "string"
                },
                "state": {
                    "description": "docker container state",
                    "type": "string"
                }
            }
        },
        "model.DepAdvertisement": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "module_id": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "model.DepAdvertisementBase": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "enum": [
                1,
                1000,
                1000000,
                1000000000
            ],
            "x-enum-varnames": [
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second"
            ]
        }
    }
}`

// SwaggerInforestricted holds exported Swagger Info so clients can modify it
var SwaggerInforestricted = &swag.Spec{
	Version:          "0.7.2",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Module Manager restricted API",
	Description:      "Provides access to selected deployment management functions.",
	InfoInstanceName: "restricted",
	SwaggerTemplate:  docTemplaterestricted,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInforestricted.InstanceName(), SwaggerInforestricted)
}
